import csv  


# The 'with open(...)' statement opens the CSV file and ensures it is automatically
# closed, even if errors occur.

with open("example_file.csv") as for_dict:
    
    # Create a DictReader object. This object reads the first line of the file 
    # as column headers (keys) and treats every subsequent row as a dictionary.

    job_on_file = csv.DictReader(for_dict)
    
    # Initialize a variable to store the cumulative sum of the salaries.
    total_salary_column = 0
    
    
    # Iterate through each row generated by the DictReader. 
    # 'row' is a dictionary containing the data for one line (e.g., {'ID': '1', 'Salary': '75000', ...}).
    for row in job_on_file:
        
        # Start a try-except block to handle potential errors during data conversion.
        try:
            # Access the value of the 'Salary' column using the header name as the key.
            # Convert the value (which is a string) into an integer.
            read_value = int(row["Salary"])
            
            # Add the successfully converted salary value to the running total.
            total_salary_column += read_value
            
        # If 'int()' fails (e.g., the cell is empty, or contains text like "N/A"), 
        # a ValueError is raised.
        except ValueError:
            
            # If an error occurs, the 'continue' statement immediately skips the rest 
            # of the code in the loop for the current row and moves to the next row. 
            # This effectively ignores non-numeric salary values.
            continue
            

# After the 'with open' block is finished (and the file is closed), print the final result.
# The f-string is used for easy formatting of the output message.

print(f"Sum of the Salary column:{total_salary_column}")